#!/bin/bash
# waydroid-patches.sh - apply the WayDroid-ATV patch stack onto an existing
# LineageOS (or AOSP-with-LineageOS) checkout, WITHOUT replacing any project.
#   ./waydroid-patches.sh manifest <source-dir> [--no-sync] [-j <n>]
#   ./waydroid-patches.sh manifest <source-dir> --no-aosp-swaps
#   ./waydroid-patches.sh apply    <source-dir> [--dry-run] [--no-sync] [-j <n>]
#   ./waydroid-patches.sh apply    <source-dir> --layer <layer>
#   ./waydroid-patches.sh apply    <source-dir> --only <project> [--only <project>...]
#   ./waydroid-patches.sh status   <source-dir>
#   ./waydroid-patches.sh abort    <source-dir>
#   ./waydroid-patches.sh revert   <source-dir> [--yes]
#   ./waydroid-patches.sh revert   <source-dir> --yes [--uninstall] [--purge-projects]
# Design notes
# Upstream WayDroid-ATV gets its changes in by remove-project'ing ~15 LineageOS
# projects from the manifest, re-adding its own forks at the same paths, then
# git am-ing base-patches-35 on top of the fork. Every LineageOS merge after
# that is a manual fork rebase.
# Here the LineageOS project is kept and patches are layered on top instead:
#   layer 10-lineage-forks  generated by tools/gen-fork-patches.sh. For each
#                           project that has a WayDroid fork, the exact commit
#                           range `merge-base .. fork tip`, where merge-base is
#                           the fork point with LineageOS. That range is only
#                           the WayDroid commits, never a LineageOS commit.
#                           Covers frameworks/base, frameworks/av,
#                           frameworks/native, hardware/interfaces, system/core,
#                           system/vold, lineage-sdk.
#                           Must be applied before layer 20.
#   layer 20-upstream       upstream's hand-written base-patches-35, vendored
#                           verbatim. These were authored against the forks, so
#                           they belong on top of layer 10.
# Patches are applied with `git am -3` (3-way) and are idempotent: a patch that
# already reverse-applies cleanly is reported as "already" and skipped.
# revert
# Puts the tree back the way it was before this repo was ever run:
#   1. aborts any in-progress git am
#   2. resets every patched project to the SHA recorded at apply time (projects
#      with no recorded SHA fall back to `repo sync -l --force-sync`, which
#      restores the manifest revision offline from the local mirror)
#   3. drops the autopatch/* tags
#   4. removes the local_manifests fragments we installed
#   5. deletes the project directories our manifest introduced (only those the
#      stock ROM manifest does not already contain)
#   6. makes repo re-resolve .repo/manifest.xml
# Without --yes it only prints the plan.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PATCH_ROOT="$SCRIPT_DIR/base-patches-35"
MANIFEST_DIR="$SCRIPT_DIR/manifest"

# Applied in this order; upstream's roms-patches act as conflict-resolution hints.
LAYERS=("10-lineage-forks" "15-ours" "20-upstream")
FALLBACK_DIR="$PATCH_ROOT/20-upstream/roms-patches"

CONFLICT_DIR="$SCRIPT_DIR/.conflicts"
STATE_FILE="$SCRIPT_DIR/.state"
MANIFEST_STATE="$SCRIPT_DIR/.manifest-state"

CONFLICTS=()
APPLIED=()
SKIPPED=()
NOTSYNCED=()
DRY_RUN=0

# Every command takes the source dir as its first argument, and it may be
# relative. It must be resolved to an absolute path before use, because the
# git-repo ownership check below compares against absolute prefixes. Leaving it
# relative makes every project look like "not synced".
resolve_src() {
  [[ -d "$src" ]] || die "$src is not a directory"
  src="$(cd "$src" && pwd)"
  [[ -d "$src/.repo" ]] || die "$src does not look like a repo checkout (no .repo)"
}

die() { echo "error: $*" >&2; exit 1; }
warn() { echo "warn: $*" >&2; }


# A patch directory is usable if it sits inside a git repo that belongs to the
# source tree. The prefix check matters: the source tree may itself live inside
# an unrelated git repository, and git walks up to find one, which would make
# every `git apply --check` silently succeed against the wrong tree.
#
# The patch layout is <project>/<file>.patch, so a patch path may be nested
# several levels below the project root in some layers; the owner is always
# found by walking up to the real repo root.
src_repo_of() {
  local top
  top="$(git -C "$1" rev-parse --show-toplevel 2>/dev/null)" || return 1
  case "$top" in
    "$src"/*) printf '%s\n' "$top" ;;
    *) return 1 ;;
  esac
}

in_git_repo() {
  src_repo_of "$1" >/dev/null 2>&1
}

owning_project() {
  local top
  top="$(src_repo_of "$src/$1")" || return 1
  printf '%s\n' "${top#"$src"/}"
}

already_applied() {
  local dir="$1" patch="$2"

  # Primary test: is this exact commit already in the history?
  #
  # A textual `git apply --reverse --check` is not sufficient. Once a later
  # patch in the same series edits the same lines, an already-applied earlier
  # patch stops reverse-applying cleanly and looks like a conflict. Matching the
  # author date plus subject, the way upstream apply-patches.sh does, is exact.
  local a b log
  a="$(sed -n 's/^Date: //p' "$patch" | head -1)"
  b="$(sed -n 's/^Subject: //p' "$patch" | head -1 | sed 's/^\[PATCH[^]]*\] *//')"
  if [[ -n "$a" && -n "$b" ]]; then
    # Capture the log rather than piping it into grep. Under `set -o pipefail`
    # a `git log | grep -q` pipeline is poisoned by SIGPIPE as soon as grep
    # exits on the first match, which silently turns a real match into a
    # failure. That only shows up on projects with a long history.
    log="$(git -C "$dir" log --max-count=10000 --pretty=format:'%aD, %s' 2>/dev/null)"
    [[ "$log" == *"$a, $b"* ]] && return 0
  fi

  # Secondary test: a patch that came from LineageOS itself and was already
  # merged upstream will not be in our log, but its content is already present.
  git -C "$dir" apply --reverse --check --whitespace=nowarn "$patch" >/dev/null 2>&1
}

tag_project() {
  local dir="$1" tag="$2"
  git -C "$dir" tag -f "$tag" >/dev/null 2>&1 || true
}

# Remember the pristine (pre-patch) HEAD of every project we touch, so revert can
# put the tree back exactly as it was, even if the manifest has moved on.
# Format: <project-path><TAB><sha>
record_pristine() {
  local dir="$1" proj="$2" sha owner
  owner="$(owning_project "$proj" || true)"
  [[ -n "$owner" ]] || return 0
  proj="$owner"
  [[ -e "$STATE_FILE" ]] || : > "$STATE_FILE"
  grep -q "^${proj}	" "$STATE_FILE" && return 0
  sha="$(git -C "$dir" rev-parse HEAD 2>/dev/null)" || return 0
  printf '%s\t%s\n' "$proj" "$sha" >> "$STATE_FILE"
}

pristine_sha() {
  [[ -f "$STATE_FILE" ]] || return 1
  awk -F'\t' -v p="$1" '$1==p {print $2; found=1} END{exit !found}' "$STATE_FILE"
}

# git am that respects --dry-run: in dry mode it applies then immediately aborts,
# so the verdict is exact without leaving any change behind.
try_am() {
  local dir="$1" patch="$2"
  if git -C "$dir" am -3 --whitespace=nowarn "$patch" >/dev/null 2>&1; then
    [[ $DRY_RUN -eq 1 ]] && git -C "$dir" am --abort >/dev/null 2>&1
    return 0
  fi
  git -C "$dir" am --abort >/dev/null 2>&1 || true
  return 1
}

wanted() {
  local proj="$1"
  [[ ${#ONLY[@]} -eq 0 ]] && return 0
  local o
  for o in "${ONLY[@]}"; do
    [[ "$proj" == "$o" ]] && return 0
  done
  return 1
}

apply_layer() {
  local layer="$1"
  local layer_dir="$PATCH_ROOT/$layer"
  [[ -d "$layer_dir" ]] || { warn "layer $layer not found, skipping"; return 0; }

  echo "layer $layer"
  local patch_list
  patch_list="$(cd "$layer_dir" && find . -path ./roms-patches -prune -o -name '*.patch' -printf '%P\n' | sort)"
  if [[ -z "$patch_list" ]]; then
    warn "no patches in $layer"
    return 0
  fi

  local p
  while IFS= read -r p; do
    [[ -n "$p" ]] || continue
    local proj="${p%/*}"
    local rel="${p##*/}"
    local dir="$src/$proj"
    local patch="$layer_dir/$p"

    wanted "$proj" || continue

    if ! in_git_repo "$dir"; then
      NOTSYNCED+=("$proj")
      continue
    fi

    if git -C "$dir" rev-parse -q --verify REBASE_HEAD >/dev/null 2>&1 \
       || [[ -d "$dir/.git/rebase-apply" || -d "$dir/.git/rebase-merge" ]]; then
      warn "project $proj has a patch/rebase in progress, resolve it first"
      CONFLICTS+=("$proj")
      continue
    fi

    if already_applied "$dir" "$patch"; then
      SKIPPED+=("$layer/$p")
      printf 'already    %s\n' "$p"
      continue
    fi

    record_pristine "$dir" "$proj"
    if try_am "$dir" "$patch"; then
      APPLIED+=("$layer/$p")
      if [[ $DRY_RUN -eq 1 ]]; then
        printf 'wouldapply %s\n' "$p"
      else
        printf 'applied    %s\n' "$p"
      fi
    else
      local fixed=0 fb
      if [[ -d "$FALLBACK_DIR" ]]; then
        for fb in "$FALLBACK_DIR"/*/; do
          [[ -d "$fb" ]] || continue
          if [[ -f "${fb}${rel}" ]] && try_am "$dir" "${fb}${rel}"; then
            printf 'resolved   %s (via %s)\n' "$p" "$(basename "$fb")"
            APPLIED+=("$layer/$p")
            fixed=1
            break
          fi
        done
      fi
      if [[ $fixed -eq 0 ]]; then
        printf 'conflict   %s\n' "$p"
        CONFLICTS+=("$proj")
        if [[ $DRY_RUN -eq 0 ]]; then
          mkdir -p "$CONFLICT_DIR/$layer"
          cp -f "$patch" "$CONFLICT_DIR/$layer/"
        fi
      fi
    fi
  done <<< "$patch_list"

  if [[ $DRY_RUN -eq 0 ]]; then
    local proj
    for proj in $(printf '%s\n' "$patch_list" | sed 's|/[^/]*$||' | sort -u); do
      in_git_repo "$src/$proj" || continue
      tag_project "$src/$proj" "autopatch/$layer"
    done
  fi
}

cmd_manifest() {
  local src="${1:?source dir required}"
  resolve_src
  shift

  # The AOSP display/media swaps are ON by default. ffmpeg's 32-bit variant
  # needs libva for android-x86, and LineageOS's external/libva only enables
  # x86_64, so without the swap the build fails in kati with
  # "libavcodec (SHARED_LIBRARIES android-x86) missing libva".
  local swaps=1 dosync=1 jobs
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --with-aosp-swaps) swaps=1; shift ;;
      --no-aosp-swaps) swaps=0; shift ;;
      --no-sync) dosync=0; shift ;;
      -j) jobs="$2"; shift 2 ;;
      -j*) jobs="${1#-j}"; shift ;;
      *) warn "unknown option $1"; shift ;;
    esac
  done
  [[ -n "${jobs:-}" ]] || jobs="$(nproc --all 2>/dev/null || nproc 2>/dev/null || echo 4)"

  local dest="$src/.repo/local_manifests"

  # Refuse to install a fragment that is not well-formed XML. An ill-formed
  # fragment makes every later `repo` command fail with a confusing error.
  local bad=0 f
  for f in $(our_manifest_files); do
    [[ -f "$f" ]] || continue
    python3 "$SCRIPT_DIR/tools/xml-paths.py" "$f" >/dev/null || bad=1
  done
  [[ $bad -eq 0 ]] || die "a manifest fragment is not well-formed XML (see errors above)"

  mkdir -p "$dest"
  local n=0
  local -a installed=()
  for f in "$MANIFEST_DIR/00-remotes.xml" "$MANIFEST_DIR/10-waydroid-projects.xml"; do
    [[ -e "$f" ]] || continue
    cp -f "$f" "$dest/"
    installed+=("$dest/$(basename "$f")")
    n=$((n+1))
  done

  if [[ $swaps -eq 1 ]]; then
    cp -f "$MANIFEST_DIR/20-aosp-swaps.xml" "$dest/"
    installed+=("$dest/20-aosp-swaps.xml")
    n=$((n+1))
    echo "installed $n fragments into $dest"
    echo "aosp swaps enabled, 6 remove-project entries, see manifest/20-aosp-swaps.xml"
  else
    rm -f "$dest/20-aosp-swaps.xml"
    echo "installed $n fragments into $dest"
    echo "aosp swaps not enabled, pure-add manifest"
    echo "external/{gmmlib,intel-media-driver,libdrm,libva,minigbm}"
    echo "keep their LineageOS versions, pass --with-aosp-swaps to override them"
  fi

  # Record exactly what we wrote so revert never has to guess.
  printf '%s\n' "${installed[@]}" > "$MANIFEST_STATE"

  # Fail loudly if a remove-project ever creeps into the default path.
  if ! python3 "$SCRIPT_DIR/tools/xml-paths.py" --no-remove \
        "$dest/00-remotes.xml" "$dest/10-waydroid-projects.xml"; then
    die "the default manifest must never contain remove-project"
  fi

  if [[ $dosync -eq 0 ]]; then
    echo "next: (cd $src && repo sync -c -j$jobs --force-sync)"
    return 0
  fi

  # A swapped project keeps a work tree that `repo` refuses to overwrite, because
  # our patches are committed on top of it. Those few need --force-sync, which
  # discards that work tree, so it must be scoped to them and done FIRST, since
  # even a plain `repo sync` fails while those stale work trees are present.
  if [[ $swaps -eq 1 && -f "$dest/20-aosp-swaps.xml" ]]; then
    local -a swapped=()
    local sp
    while IFS= read -r sp; do
      [[ -n "$sp" ]] && swapped+=("$sp")
    done < <(python3 "$SCRIPT_DIR/tools/xml-paths.py" "$dest/20-aosp-swaps.xml")
    if [[ ${#swapped[@]} -gt 0 ]]; then
      echo
      echo "force-syncing the ${#swapped[@]} swapped project(s) to pick up the forks:"
      printf '  %s\n' "${swapped[@]}"
      if ! ( cd "$src" && repo sync -c -j"$jobs" --force-sync "${swapped[@]}" ); then
        echo
        echo "force-sync of the swapped projects failed."
        return 1
      fi
    fi
  fi

  echo
  echo "syncing the rest (repo sync -c -j$jobs --force-sync), this can take a while..."
  if ! ( cd "$src" && repo sync -c -j"$jobs" --force-sync ); then
    echo
    echo "repo sync failed. Fix that, then run:"
    echo "  (cd $src && repo sync -c -j$jobs --force-sync)"
    return 1
  fi

  echo
  echo "sync finished, ready for: $0 apply $src"
}

cmd_apply() {
  local dry=0 dosync=1 jobs swaps=1
  local -a layers=()
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --dry-run|-n) dry=1; shift ;;
      --no-aosp-swaps) swaps=0; shift ;;
      --no-sync) dosync=0; shift ;;
      -j) jobs="$2"; shift 2 ;;
      -j*) jobs="${1#-j}"; shift ;;
      --layer) layers+=("$2"); shift 2 ;;
      --only)  ONLY+=("$2");  shift 2 ;;
      *) warn "unknown option $1"; shift ;;
    esac
  done
  [[ ${#layers[@]} -gt 0 ]] || layers=("${LAYERS[@]}")
  [[ -n "${jobs:-}" ]] || jobs="$(nproc --all 2>/dev/null || nproc 2>/dev/null || echo 4)"

  resolve_src
  [[ -d "$src/build" ]] || warn "$src has no build/ dir, is this an AOSP/LineageOS tree?"

  # `revert` removes the manifest fragments, so re-applying has to put them back.
  # Doing it here makes `apply` self-sufficient: one command, correct state,
  # whether or not `manifest` was run first.
  local mdir="$src/.repo/local_manifests"
  local want_swaps="$mdir/20-aosp-swaps.xml"
  local need_manifest=0
  [[ -f "$mdir/00-remotes.xml" ]] || need_manifest=1
  [[ -f "$mdir/10-waydroid-projects.xml" ]] || need_manifest=1
  if [[ $swaps -eq 1 ]]; then
    [[ -f "$want_swaps" ]] || need_manifest=1
  else
    [[ -f "$want_swaps" ]] && need_manifest=1
  fi
  if [[ $need_manifest -eq 1 ]]; then
    echo "manifest fragments are not installed, installing them"
    if [[ $swaps -eq 1 ]]; then
      cmd_manifest "$src" --no-sync --with-aosp-swaps >/dev/null \
        || die "could not install the manifest fragments"
    else
      cmd_manifest "$src" --no-sync --no-aosp-swaps >/dev/null \
        || die "could not install the manifest fragments"
    fi
    echo "installed"
  fi

  # The patches under vendor/intel/*, external/llvm-project and friends live in
  # projects that only exist because of our manifest. If they are not on disk
  # yet those patches are silently skipped, so sync first.
  local -a absent=()
  local p
  while IFS= read -r p; do
    [[ -n "$p" ]] || continue
    [[ -d "$src/$p" ]] || absent+=("$p")
  done < <(our_projects)

  if [[ ${#absent[@]} -gt 0 ]]; then
    if [[ $dosync -eq 0 ]]; then
      echo
      echo "error: ${#absent[@]} project(s) from our manifest are missing and --no-sync was given:"
      printf '  %s\n' "${absent[@]}"
      echo "run: (cd $src && repo sync -c -j$jobs --force-sync)"
      return 1
    fi
    if [[ $dry -eq 1 ]]; then
      # A dry run must not download half a tree.
      echo
      echo "dry run: ${#absent[@]} project(s) from our manifest are missing and would be synced:"
      printf '  %s\n' "${absent[@]}"
    else
      echo "${#absent[@]} project(s) from our manifest are not in the tree, syncing first."
      echo "this downloads them, so it can take a while."
      echo
      if ! ( cd "$src" && repo sync -c -j"$jobs" --force-sync ); then
        echo
        echo "repo sync failed. Fix that, then re-run: $0 apply $src"
        return 1
      fi
      echo
      echo "sync finished"
    fi
  fi

  if [[ $dry -eq 1 ]]; then
    DRY_RUN=1
    echo "dry run, nothing will be modified"
  fi

  local l
  for l in "${layers[@]}"; do
    apply_layer "$l"
    if [[ $dry -eq 0 && ${#CONFLICTS[@]} -gt 0 ]]; then
      break
    fi
  done

  # Projects that are not in the tree at all. Reported once per project rather
  # than once per patch, otherwise a missing checkout buries the real output.
  local -a missing=()
  declare -A seen_missing=()
  local proj
  for proj in "${NOTSYNCED[@]}"; do
    [[ -n "${seen_missing[$proj]:-}" ]] && continue
    seen_missing["$proj"]=1
    missing+=("$proj")
  done

  local total=$(( ${#APPLIED[@]} + ${#SKIPPED[@]} ))
  echo
  echo "applied: ${#APPLIED[@]}  already: ${#SKIPPED[@]}  conflicts: ${#CONFLICTS[@]}  not-synced: ${#NOTSYNCED[@]}"

  if [[ ${#missing[@]} -gt 0 ]]; then
    echo
    echo "these projects are not in the tree, their patches were skipped:"
    printf '  %s\n' "${missing[@]}"
    echo
    echo "if you have not synced them yet:  $0 manifest $src && (cd $src && repo sync -c -j\$(nproc --all))"
  fi

  if [[ ${#CONFLICTS[@]} -gt 0 ]]; then
    echo
    echo "conflicting projects:"
    printf '%s\n' "${CONFLICTS[@]}" | sort -u | sed 's/^/  /'
    echo
    echo "conflicting patches were copied to $CONFLICT_DIR"
    echo "continue by hand:  cd <source>/<project> && git am -3 <patch>"
    echo "give up:           waydroid-patches.sh abort <source-dir>"
    exit 1
  fi

  # Nothing at all was applied and nothing was recognised as already present.
  # That means the patches were skipped wholesale, not that we are done.
  if [[ $total -eq 0 && ${#NOTSYNCED[@]} -gt 0 ]]; then
    echo
    echo "error: no patch could be applied and none was recognised as present."
    echo "       every patch was skipped because its project is not in the tree."
    return 1
  fi

  echo "all patches applied"
}

patched_projects() {
  local layer
  for layer in "${LAYERS[@]}"; do
    [[ -d "$PATCH_ROOT/$layer" ]] || continue
    # strip the file name to leave the project path
    (cd "$PATCH_ROOT/$layer" && find . -path ./roms-patches -prune -o -name '*.patch' -printf '%P\n' | sed 's|/[^/]*$||')
  done | sort -u
}

# The manifest fragments this repo is allowed to install and later remove.
our_manifest_files() {
  local f
  for f in 00-remotes.xml 10-waydroid-projects.xml 20-aosp-swaps.xml; do
    printf '%s\n' "$MANIFEST_DIR/$f"
  done
}

# Project paths declared in our own manifest fragments. Parsed with a real XML
# parser because the fragments carry documentation comments that contain example
# paths (e.g. path="X") which must not be mistaken for real entries.
our_projects() {
  local f
  for f in $(our_manifest_files); do
    [[ -f "$f" ]] || continue
    python3 "$SCRIPT_DIR/tools/xml-paths.py" "$f"
  done | sort -u
}

# Project paths declared by the stock ROM manifests (excludes local_manifests).
base_projects() {
  find "$src/.repo/manifests" -name '*.xml' 2>/dev/null \
    | xargs -r grep -ho 'path="[^"]*"' 2>/dev/null \
    | sed 's/^path="//;s/"$//' | sort -u
}

cmd_revert() {
  local do=0 keep_manifest=1 purge=0
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --dry-run|-n) shift ;;
      --yes|-y)     do=1; shift ;;
      --keep-manifest) keep_manifest=1; shift ;;
      --purge-projects) purge=1; keep_manifest=0; shift ;;
      --uninstall)      keep_manifest=0; shift ;;
      *) warn "unknown option $1"; shift ;;
    esac
  done

  [[ -d "$src/.repo" ]] || die "$src does not look like a repo checkout (no .repo)"
  src="$(cd "$src" && pwd)"

  local -a plan_projects=()
  local p
  while IFS= read -r p; do
    [[ -n "$p" ]] && plan_projects+=("$p")
  done < <(patched_projects)

  local -a base=() ours=() added=()
  mapfile -t base < <(base_projects)
  if [[ $keep_manifest -eq 0 ]]; then
    mapfile -t ours < <(our_projects)
    # A project is ours only if the stock manifests do not already have it.
    declare -A seen=()
    local b
    for b in "${base[@]}"; do seen["$b"]=1; done
    for p in "${ours[@]}"; do [[ -n "${seen[$p]:-}" ]] || added+=("$p"); done
  fi

  echo "revert plan for $src"
  echo
  echo "1. reset patched projects to pre-patch state"
  local proj sha cur owner
  declare -A planned=()
  for proj in "${plan_projects[@]}"; do
    owner="$(owning_project "$proj" || true)"
    [[ -n "$owner" ]] || continue
    planned["$owner"]=1
  done
  for owner in "${!planned[@]}"; do
    cur="$(git -C "$src/$owner" rev-parse --short HEAD 2>/dev/null)"
    sha="$(pristine_sha "$owner" || true)"
    printf '   %-34s %-10s -> %s\n' "$owner" "$cur" "${sha:0:12}${sha:+(recorded)}${sha:-(not recorded)}"
  done

  if [[ $keep_manifest -eq 0 ]]; then
    echo
    echo "2. remove local_manifest fragments (--uninstall / --purge-projects)"
    local f
    if [[ -f "$MANIFEST_STATE" ]]; then
      while IFS= read -r f; do
        [[ -n "$f" ]] || continue
        printf '   %-60s %s\n' "$f" "$([[ -e "$f" ]] && echo present || echo already gone)"
      done < "$MANIFEST_STATE"
    else
      echo "   (nothing recorded, no fragments were installed by us)"
    fi
    echo
    if [[ $purge -eq 1 ]]; then
      echo "3. DELETE projects added by that manifest (${#added[@]})"
      for p in "${added[@]}"; do
        printf '   %-48s %s\n' "$p" "$([[ -e "$src/$p" ]] && echo present || echo absent)"
      done
    else
      echo "3. keep the ${#added[@]} added project(s) (use --purge-projects to delete them)"
      echo "   they are plain synced checkouts; keeping them means re-applying needs no re-sync"
    fi
  else
    echo
    echo "2/3. manifest fragments and added projects are left in place"
    echo "     this is what makes re-apply instant: use --uninstall to remove them"
  fi
  echo

  if [[ $do -ne 1 ]]; then
    echo "dry run, pass --yes to actually revert"
    return 0
  fi

  echo "reverting"

  # Clear in-progress am/rebase state.
  for owner in "${!planned[@]}"; do
    local d="$src/$owner"
    if [[ -d "$d/.git/rebase-apply" || -d "$d/.git/rebase-merge" ]]; then
      git -C "$d" am --abort >/dev/null 2>&1 && echo "   aborted in-progress am: $owner"
    fi
  done

  # Reset to the recorded pristine SHA. This is offline, no repo sync needed.
  local -a fallback=()
  declare -A seen_owner=()
  for owner in "${!planned[@]}"; do
    [[ -n "${seen_owner[$owner]:-}" ]] && continue
    seen_owner["$owner"]=1
    local d="$src/$owner"
    sha="$(pristine_sha "$owner" || true)"
    if [[ -n "$sha" ]] && git -C "$d" cat-file -e "$sha^{commit}" 2>/dev/null; then
      git -C "$d" reset --hard -q "$sha" && echo "   reset $owner -> ${sha:0:12}"
    else
      fallback+=("$owner")
    fi
    local t
    for t in $(git -C "$d" tag -l 'autopatch/*'); do
      git -C "$d" tag -d "$t" >/dev/null 2>&1
    done
  done

  # Projects with no recorded SHA: let repo restore the manifest revision.
  # Only hand repo projects it actually knows about, otherwise it errors out.
  if [[ ${#fallback[@]} -gt 0 ]]; then
    local -a known=()
    declare -A inbase=()
    local b
    mapfile -t base < <(base_projects)
    for b in "${base[@]}"; do inbase["$b"]=1; done
    for owner in "${fallback[@]}"; do
      [[ -n "${inbase[$owner]:-}" ]] && known+=("$owner")
    done
    if [[ ${#known[@]} -gt 0 ]]; then
      warn "no recorded pristine SHA for ${#known[@]} project(s), using repo sync -l --force-sync"
      if ( cd "$src" && repo sync -l --force-sync "${known[@]}" ) >/dev/null 2>&1; then
        echo "   repo restored: ${known[*]}"
      else
        warn "repo sync failed for: ${known[*]}"
      fi
    fi
    for owner in "${fallback[@]}"; do
      [[ -n "${inbase[$owner]:-}" ]] || echo "   note: $owner is not a manifest project, left alone"
    done
  fi

  if [[ $keep_manifest -eq 0 ]]; then
    if [[ -f "$MANIFEST_STATE" ]]; then
      while IFS= read -r f; do
        [[ -n "$f" && -e "$f" ]] || continue
        rm -f "$f" && echo "   removed $f"
      done < "$MANIFEST_STATE"
      rm -f "$MANIFEST_STATE"
    fi
    rmdir "$src/.repo/local_manifests" 2>/dev/null && echo "   removed empty .repo/local_manifests/"

    if [[ $purge -eq 1 ]]; then
      for p in "${added[@]}"; do
        if [[ -d "$src/$p" ]]; then
          rm -rf "${src:?}/$p" && echo "   deleted project $p"
        fi
      done
    fi

    # Let repo re-resolve .repo/manifest.xml without local_manifests.
    if ( cd "$src" && repo sync -l --detach ) >/dev/null 2>&1; then
      echo "   repo manifest re-resolved, run 'repo sync' to fetch the new projects"
    else
      warn "could not re-resolve .repo/manifest.xml automatically, run 'repo sync' manually"
    fi
  fi

  rm -rf "$CONFLICT_DIR"
  rm -f "$STATE_FILE"
  echo "   removed $STATE_FILE and $CONFLICT_DIR"

  echo
  echo "revert complete"
  echo "next: (cd $src && repo sync)"
}

cmd_abort() {
  resolve_src
  local proj
  while IFS= read -r proj; do
    in_git_repo "$src/$proj" || continue
    if [[ -d "$src/$proj/.git/rebase-apply" || -d "$src/$proj/.git/rebase-merge" ]]; then
      git -C "$src/$proj" am --abort >/dev/null 2>&1 && echo "aborted: $proj"
    fi
  done < <(patched_projects)
}

cmd_status() {
  resolve_src
  printf '%-34s %-24s %-8s %s\n' PROJECT TAGS APPLIED TOTAL
  local layer rel proj dir total applied tagged
  while IFS= read -r proj; do
    dir="$src/$proj"
    in_git_repo "$dir" || continue
    total=0
    applied=0
    for layer in "${LAYERS[@]}"; do
      [[ -d "$PATCH_ROOT/$layer/$proj" ]] || continue
      while IFS= read -r rel; do
        total=$((total+1))
        already_applied "$dir" "$PATCH_ROOT/$layer/$proj/$rel" && applied=$((applied+1))
      done < <(cd "$PATCH_ROOT/$layer/$proj" && find . -name '*.patch' -printf '%P\n')
    done
    # Join with a comma: a project patched by both layers has two tags, and
    # space-separating them would shift every later column.
    tagged="$(git -C "$dir" tag -l 'autopatch/*' | sort | paste -sd, -)"
    printf '%-34s %-24s %-8s %s\n' "$proj" "${tagged:-none}" "$applied" "$total"
  done < <(patched_projects)
}

usage() {
  sed -n '2,/^set -/p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//;$d'
}

src=""
ONLY=()
cmd="${1:-}"; shift || true
case "$cmd" in
  manifest) src="${1:?source dir required}"; shift; cmd_manifest "$src" "$@" ;;
  apply)    src="${1:?source dir required}"; shift; cmd_apply "$@" ;;
  abort)    src="${1:?source dir required}"; cmd_abort ;;
  revert)   src="${1:?source dir required}"; shift; cmd_revert "$@" ;;
  status)   src="${1:?source dir required}"; cmd_status ;;
  ""|-h|--help|help) usage ;;
  *) echo "unknown command: $cmd" >&2; usage; exit 1 ;;
esac
